spring:
  cloud:
    config:
      server:
        git:
          #uri: C:\work\ksr\kolkata2020labsconfig
          uri: https://github.com/pradipeeda/handson.git
          searchPaths: ConfigData
          skipSslValidation: true

server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'