--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: convertcurrencyms
    version: v1
  name: convertcurrencyms
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: convertcurrencyms
      version: v1
  template: 
    metadata: 
      labels: 
        app: convertcurrencyms
        version: v1

    spec: 

      containers: 
        - 
          image: "pradip1983/convertcurrencymshandson"
          imagePullPolicy: Always
          name: convertcurrencyms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8081
            hostPort: 8081      
          env:
 #           - name: productms.configserverurl
 #             value: "http://configserver:8888"
            - name: productms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    